import { Worker, Job } from 'bullmq';
import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';

dotenv.config();

const prisma = new PrismaClient();

const redisConnection = {
  host: process.env.REDIS_HOST || 'localhost',
  port: parseInt(process.env.REDIS_PORT || '6379'),
  maxRetriesPerRequest: null,
};

// This is the mock for the LLM API. In a real system, you'd integrate OpenAI or similar.
async function generatePlaywrightScript(description: string): Promise<string> {
  // Simulate LLM delay
  await new Promise((resolve) => setTimeout(resolve, 2000));

  return `import { test, expect } from '@playwright/test';

test('Generated test for: ${description}', async ({ page }) => {
  // 1. Navigate to base URL (assumed)
  await page.goto('https://example.com');

  // 2. Perform actions based on description
  // Note: These are mocked steps generated by the Authoring Agent
  console.log("Executing generated steps...");

  // Example assertions
  await expect(page).toHaveTitle(/Example Domain/);
});
`;
}

// Mock Analysis Agent logic to propose selector fixes
async function analyzeFailureAndProposeFix(testId: string, errorLog: string): Promise<any> {
  await new Promise((resolve) => setTimeout(resolve, 1500));

  return {
    probableCause: "UI change: The selector '#old-button' could not be found.",
    confidence: 0.85,
    suggestedFixes: [
      {
        originalSelector: "#old-button",
        proposedSelector: "button:has-text('Submit')",
        rationale: "Found a button with the text 'Submit' in the same DOM vicinity."
      }
    ]
  };
}

// 1. Authoring Agent Worker
const authoringWorker = new Worker(
  'test-generation',
  async (job: Job) => {
    const { testId, nl_description, settings } = job.data;
    console.log(`[Authoring Agent] Processing job for test ${testId}`);

    try {
      const generatedScript = await generatePlaywrightScript(nl_description);

      // Update the test record with the generated code
      await prisma.test.update({
        where: { id: testId },
        data: {
          source: {
            type: 'code',
            original_description: nl_description,
            settings: settings,
            code: generatedScript,
            status: 'ready'
          }
        }
      });

      console.log(`[Authoring Agent] Successfully generated script for test ${testId}`);
      return { success: true, testId };
    } catch (error) {
      console.error(`[Authoring Agent] Failed to generate script for test ${testId}`, error);
      throw error;
    }
  },
  { connection: redisConnection }
);

// 2. Analysis Agent Worker (Listens for execution failures)
const analysisWorker = new Worker(
  'test-analysis',
  async (job: Job) => {
    const { testId, errorLog } = job.data;
    console.log(`[Analysis Agent] Analyzing failure for test ${testId}`);

    try {
      const analysisResult = await analyzeFailureAndProposeFix(testId, errorLog);

      // We would normally store this in a "Runs" or "Insights" table
      // Here we append it to the test's appliedAgentFixes for MVP demonstration

      const test = await prisma.test.findUnique({ where: { id: testId }});
      const currentFixes = Array.isArray(test?.appliedAgentFixes) ? test.appliedAgentFixes : [];

      await prisma.test.update({
        where: { id: testId },
        data: {
          appliedAgentFixes: [...currentFixes, { timestamp: new Date(), ...analysisResult }]
        }
      });

      console.log(`[Analysis Agent] Proposed fixes for test ${testId}:`, analysisResult.suggestedFixes);
      return { success: true, testId, analysisResult };
    } catch (error) {
      console.error(`[Analysis Agent] Failed to analyze test ${testId}`, error);
      throw error;
    }
  },
  { connection: redisConnection }
);


[authoringWorker, analysisWorker].forEach(w => {
  w.on('completed', job => {
    console.log(`Job ${job.id} has completed on queue ${w.name}!`);
  });

  w.on('failed', (job, err) => {
    console.error(`Job ${job?.id} has failed on queue ${w.name} with ${err.message}`);
  });
});

console.log('Orchestrator workers started. Listening for "test-generation" and "test-analysis" jobs...');
